# Server configuration
server:
  port: 9000

# Spring configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    name: ${DATABASE_NAME:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
