# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: BKg0UtJJiHJ308AE71Liv89kahDyCEUV
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://habit-application.us.auth0.com/
