### Post habit-hello-world to create first habit
POST http://localhost:9000/api/habit/create
Content-Type: application/json

{
    "name": "habit-hello-world",
    "description": "My very first habit"
}

### Get all habits
GET http://localhost:9000/api/habit



