### create habit
POST http://localhost:9000/api/habit/create
Content-Type: application/json

{
    "name": "hello-world",
    "description": "My very first habit"
}

### get all habits
GET http://localhost:9000/api/habit
Content-Type: application/json

### get habit
GET http://localhost:9000/api/habit/hello-world

### update habit
POST http://localhost:9000/api/habit/update
Content-Type: application/json

{
    "name": "hello-world",
    "description": "My very first habit has been updated"
}
